/*
 * Copyright (c) 
 * 2019-2021 Philippe Helluy <helluy@math.unistra.fr>
 * 2020-2021 Pierre Gerhard <pierre.gerhard@gmail.com>
 *
 * gdon3d is free software; you can redistribute it and/or modify
 * it under the terms of the GPLv3 license. See LICENSE for details.
 */
#ifndef NODE_H
#define NODE_H

#include <gdon3d.h>

typedef struct Node {
	gdn_real x[3]; /* 3D Coordinates x,y,z */
	int rank_e; /* Global rank when generated by a loop over elements */
	int rank_c; /* Global rank when sorted by lexicographic coordinates */
	int n_copy; /* Store how many time this node were already found */

	int id_node; /* (0, 1, 2, ..., 9) T10 local node id */
	int id_elem; /* Id from the element it belongs to */
} Node;

int mesh_node_compare_coordinate(const void *a, const void *b);

int mesh_node_compare_elem_id(const void *a, const void *b);

void mesh_node_print_node(Node *node, int node_index);

void mesh_node_print_node_list(Node *list_node, int list_size, char *list_name);
#endif